#!/usr/bin/php
<?php
/*
@Version : 3.0
@Author : Nitish Kumar (NinzaHost)
*/

@ob_start();
@error_reporting(0);

$data=file_get_contents('https://raw.githubusercontent.com/CpanelInc/tech-cp_license_troubleshooter/master/shenanigans.txt');
$ex=explode("\n",$data);


foreach($ex as $x){
  
 if(file_exists($x)){
   echo $x;
   echo "\n";
 }
  
}
